name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run server
        run: npm run mail-server

      - name: Send mail
        uses: ./
        with:
          connection_url: smtp://localhost:1025
          to: obiwan@example.com,yoda@example.com
          from: Luke Skywalker <luke@example.com>
          subject: Test subject
          body: Test body
          html_body: <h1>Test HTML</h1>
          attachments: README.md
          convert_markdown: true
          priority: high
          # TODO
  script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: npm run test
